name: Pyrograms
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab=4.1.6
  - numpy=1.26.4
  - matplotlib=3.8.4
  - pandas=2.2.2
  - bokeh=3.4.1
  - netcdf4=1.6.5
  - pip:
    - randomcolor==0.4.4.6
    - peakutils==1.3.4
    - threddsclient==0.4.3
