name: pyrograms
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - jupyter=1.0.0
  - notebook=6.2.0
  - numpy=1.20.0
  - pandas=1.2.1
  - bokeh=2.2.3
  - netCDF4=1.5.3
  - pip:
    - randomcolor==0.4.4.5
    - peakutils==1.3.3
